version: '3.8'
services:
  postgres:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=${PGDATABASE:?error}
      - POSTGRES_USER=${PGUSER:?error}
      - POSTGRES_PASSWORD=${PGPASSWORD:?error}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed/postgres:/docker-entrypoint-initdb.d
    ports:
      - "${PGPORT:?error}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  neo4j:
    container_name: neo4j
    image: neo4j:5.18.1-community-bullseye
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:?error}
    volumes:
      - neo4j_data:/data
      - ./seed/neo4j:/var/lib/neo4j/import
    command:
      - /bin/bash
      - -c
      - |
        neo4j-admin database import full \
          --nodes=Product=import/00-products-flipkart.csv \
          --nodes=ShoppingCart=import/01-shopping-carts-nodes.csv \
          --relationships=ORDERED=import/02-shopping-carts-relationships.csv
        /startup/docker-entrypoint.sh neo4j
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
volumes:
  postgres_data:
  neo4j_data:
