// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Category    []string
	ImageUrl    string
	Price       int32
}
